colrev.exceptions.RecordNotFoundInPrepSourceException
=====================================================

.. currentmodule:: colrev.exceptions

.. autoexception:: RecordNotFoundInPrepSourceException
